{% set name = "single-sample-gsea" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/single_sample_gsea-{{ version }}.tar.gz
  sha256: 47c971c449b1711ce653c2db09299f3bef720ddf137895f502f5ee0e72290026

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - numba

test:
  imports:
    - single_sample_gsea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Single Sample GSEA
  dev_url: https://github.com/JakaKokosar/single-sample-GSEA
  doc_url: https://doi.org/10.1038/nature08460
  home: https://github.com/JakaKokosar/single-sample-GSEA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
